services:
  - type: web
    name: hr-team
    env: python
    buildCommand: |
      pip install -r requirements.txt
      echo "Running migrations..."
      python manage.py migrate --verbosity=2
      echo "Migrations completed!"
      python manage.py showmigrations
    startCommand: gunicorn hr_team.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4 